eureka:
  instance:
    prefer-ip-address: true
  client: 
    serviceUrl: 
      defaultZone: http://orchestration-service:1111/eureka/

      
spring:
  cloud:
    stream:
      default:
        contentType: application/json
        binder: rabbit
  rabbitmq:
    host: rabbit
  data:
   elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: es:9300 
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)
  zipkin:
    baseUrl: http://zipkin:9411
    enabled: true


security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/auth/users/current

application:
  name:
    auth: auth-service
    oracle: oracle-service
    entrance: entrance-service
    
    
logging: 
  config: http://config-service:8888/${spring.application.name}/${spring.profiles.active:default}/${spring.cloud.config.label:master}/logback-spring.xml
  level: 
    root: WARN
    org.springframework: INFO

    
logstash:
  host: logstash
  port: 4560
    
    
build: 
  version: "@project.version@"  
    