eureka: 
  instance: 
    leaseRenewalIntervalInSeconds: 5
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/
      
spring:
  cloud:
    stream:
      default:
        contentType: application/json
        binder: rabbit
  data:
   elasticsearch:
    cluster-name: delphi
    cluster-nodes: localhost:9300

#for now..
management:
  security:
    enabled: false
    
logging: 
  level: 
    root: WARN
    org.springframework: INFO