spring:
  cloud:
    stream:
      default:
        contentType: application/json
        binder: rabbit
  rabbitmq:
    host: rabbit
  data:
   elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: es:9300 
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)
  zipkin:
    baseUrl: http://zipkin:9411
    enabled: true


security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/auth/users/current
      
application:
  name:
    auth: auth-service
    oracle: oracle-service
    doorway: doorway-service
    lumberjack: lumberjack
    
#TODO: loadbalanced request on logging.config. Somewhere near LoggingApplicationContextInitializer    
logging: 
  config: http://config-service:8888/config/${spring.application.name}/${spring.profiles.active:default}/${spring.cloud.config.label:master}/logback-spring.xml
  level: 
    root: WARN
    org.springframework: INFO

    
logstash:
  host: logstash
  port: 4560
    
    
build: 
  version: "@project.version@"  
    