eureka: 
  instance: 
    leaseRenewalIntervalInSeconds: 5
  client: 
    serviceUrl: 
      defaultZone: http://orchestration-service:1111/eureka/
      
spring:
  cloud:
    stream:
      default:
        contentType: application/json
        binder: rabbit
  data:
   elasticsearch:
    cluster-name: elasticsearch
    cluster-nodes: es:9300
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*)

logging: 
  config: http://config:8888/${spring.application.name}/${spring.profiles.active:default}/${spring.cloud.config.label:master}/logback-spring.xml
  level: 
    root: WARN
    org.springframework: INFO

logstash:
  host: 127.0.0.1
  port: 4560
    
build: 
  version: "@project.version@"  
    