server: 
  port: 3333
  servlet:
    context-path: /entrance

spring:
  cloud:
    stream:
      rabbit:
        bindings:
          spectre:
            producer:
              exchangeType: direct
              routingKeyExpression: '''eavesdrop'''

security:
  oauth2:
    client:
      clientId: entrance-service
      clientSecret: entrance-service-secret
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      scope: resource-server-read
      
logging: 
  level.guru.bonacci.oogway.entrance: INFO
  
file.name.answers.to.win.time: answers-to-win-time.txt

demo.message: You could start now, and spend another forty years learning about the sea without running out of new things to know.
  