server: 
  port: 6666

spring:
  cloud:
    stream:
# no content-type:json here. the message is sent from logstash where headers cannot be set
      default:
        contentType: null
      bindings:
        enrichment:
          group: localtimer

logging: 
  level.guru.bonacci.spectre.localtimer: INFO
  
geo.name.username: leonardobonacci