server:
  port: 11235
  servlet:
    context-path: /lumber

spring:
  data:
    mongodb:
      host: mongo
      database: oogway
      port: 27017

logging: 
  level.guru.bonacci.oogway.lumberjack: INFO  