server: 
  port: 4444

spring:
  cloud:
    stream:
      bindings:
        sannya: 
          group: oracle

build: 
  version: "@project.version@"

logging: 
  level.guru.bonacci.oogway.oracle: INFO
  file: C:\\logs\\oogway\\oracle.log