server: 
  port: 4444

spring:
  cloud:
    stream:
      bindings:
        sannya: 
          group: oracle

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:5000/auth/user

build: 
  version: "@project.version@"

logging: 
  level.guru.bonacci.oogway.oracle: INFO