server: 
  port: 4444
  context-path: /oracle

spring:
  cloud:
    stream:
      bindings:
        sannya: 
          group: oracle

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:5000/auth/user

logging: 
  level.guru.bonacci.oogway.oracle: INFO