server:
  port: 2222
  servlet:
    context-path: /sannyas

spring:
  cloud:
    stream:
      bindings:
        oracle:
          group: sannyas

logging:
  level.guru.bonacci.oogway.sannyas: INFO

# URLs of web pages we visit
web:
  url:
    gr: https://www.goodreads.com/quotes/tag/
    bq: https://www.brainyquote.com/quotes/keywords/#tag#_#page#.html?vm=l

# Filter configs
filter:
  maxlength: 144
  profanity.file.name: badwords.txt

proxy:
  enabled: false
#if true, supply proxy details
#  host: 127.0.0.1
#  port: 9050
#  type: SOCKS

  