server: 
  port: 3333

spring:
  cloud:
    stream:
      rabbit:
        bindings:
          spectre:
            producer:
              exchangeType: direct
              routingKeyExpression: '''eavesdrop'''

build: 
  version: "@project.version@"

logging: 
  level.guru.bonacci.oogway.web: INFO
  
file.name.answers.to.win.time: answers-to-win-time.txt

demo.message: You could start now, and spend another forty years learning about the sea without running out of new things to know.
  