server: 
  port: 3333
  context-path: /webby

spring:
  cloud:
    stream:
      rabbit:
        bindings:
          spectre:
            producer:
              exchangeType: direct
              routingKeyExpression: '''eavesdrop'''

# no need to secure the web ui 
# avoid message: 'requesting your username and password. The site says: "Spring"'
security.ignored: /**

security:
  oauth2:
    client:
      clientId: web-service
      clientSecret: web-service-secret
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: resource-server-read

logging: 
  level.guru.bonacci.oogway.web: INFO
  
file.name.answers.to.win.time: answers-to-win-time.txt

demo.message: You could start now, and spend another forty years learning about the sea without running out of new things to know.
  