server: 
  port: 3333

spring:
  cloud:
    stream:
      rabbit:
        bindings:
          spectre:
            producer:
              exchangeType: direct
              routingKeyExpression: '''eavesdrop'''

build: 
  version: "@project.version@"

logging: 
  level.guru.bonacci.oogway.web: INFO
  file: C:\\logs\\oogway\\web.log
  
file.name.answers.to.win.time: answers-to-win-time.txt

message: old woman and the sea!
  