server:
  port: 2222

spring:
  cloud:
    stream:
      bindings:
        oracle:
          group: sannya

build:
  version: "@project.version@"

logging:
  level.guru.bonacci.oogway.sannya: INFO
  file: C:\\logs\\oogway\\sannya.log

# URLs of web pages we visit
web:
  url:
    gr: https://www.goodreads.com/quotes/tag/
    bq: https://www.brainyquote.com/quotes/keywords/#tag#_#page#.html?vm=l
    qd: https://www.quotesdaddy.com/find/quote/#tag#/1

# Filter configs
filter:
  maxlength: 144
  profanity.file.name: badwords.txt

proxy:
  enabled: false
#if true, supply proxy details
#  host: 127.0.0.1
#  port: 9050
#  type: SOCKS

  